version: "3.9"

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mysite_db
      - POSTGRES_USER=user1
      - POSTGRES_PASSWORD=1234
  web:
    build: .
    command: bash -c "
      python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=mysite_DB
      - POSTGRES_USER=user1
      - POSTGRES_PASSWORD=1234
    depends_on:
      - db

